version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grok-tokyo-events
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - XAI_API_KEY=${XAI_API_KEY}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - PORT=3000
    volumes:
      - ./:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
